# Generated by Django 5.2.1 on 2025-05-31 10:06

import devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_hash_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedocument',
            name='file',
            field=models.FileField(upload_to=devices.models.device_document_upload_to),
        ),
    ]
