# Generated by Django 5.2.1 on 2025-05-31 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_devicedocument_file'),
        ('devices', '0005_device_hash_id_unique'),
    ]

    operations = [
    ]
