# Generated by Django 5.2.1 on 2025-06-02 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_merge_20250531_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Açık'), ('in_progress', 'İşlemde'), ('resolved', 'Çözüldü'), ('closed', 'Kapalı')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('updated_by', models.CharField(blank=True, max_length=255)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='fault_attachments/')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='devices.device')),
            ],
        ),
    ]
