# Generated by Django 5.2.1 on 2025-06-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_faultrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faultrecord',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='faultrecord',
            name='created_by',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='faultrecord',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
